apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
  namespace: default
  labels:
    app: kubernetes-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubernetes-demo
  template:
    metadata:
      labels:
        app: kubernetes-demo
    spec:
      containers:
      - name: httpd
        image: nginx:latest
        ports:
        - containerPort: 80

apiVersion: v1
kind: Service
metadata:
  name: demo-service
  namespace: default
  labels:
    app: kubernetes-demo
spec:
  selector:
    app: kubernetes-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
